services:
  enterprise-rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-rag-service
    network_mode: host
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - EMBEDDING_MODEL_NAME=BAAI/bge-small-en-v1.5
      - QDRANT_COLLECTION_NAME=enterprise_knowledge_base
      - QDRANT_STORAGE_PATH=/home/appuser/service/data/qdrant_storage
      - HF_HOME=/home/appuser/.cache/huggingface
    restart: always
